""" The "State" is the shared memory that all nodes in your graph can read and write to."""

from typing import TypedDict, List, Annotated
import operator

class AgentState(TypedDict):
    # The 'Annoated part tells LangGraph to 'append to the list instead of overwriting it.
    messages: Annotated[List[str], operator.add] # A list of all messages in the conversation, including system prompts, user inputs, and agent responses. This is the "memory" of the conversation that the agent can refer back to.
    figma_data: dict # A dictionary to store the latest Figma design data retrieved by the agent. This allows the agent to keep track of the design specifications it has fetched and use them in subsequent interactions.
    generated_code: dict # A dictionary to store the latest code generated by the agent. This allows the agent to keep track of the code snippets it has created and refer back to them when needed, such as when making improvements or debugging.
    errors: List[str] # A list to store any error messages encountered during the agent's operations. This helps the agent keep track of issues that arise and can be used for debugging or improving future responses.
    current_task: str # A string to store the current task or objective that the agent is working on. This helps the agent maintain focus and context as it interacts with the user and performs various actions.
    is_complete: bool # A boolean flag to indicate whether the current task has been completed. This allows the agent to know when it has successfully finished a task and can move on to the next one or end the conversation.
